#!/bin/bash

cat h1.txt | grep IP | sed 's/00:0/ 00:0/' | tr -s ' ' | cut -d' ' -f2,9,18 | cut -d')' -f1 | sed 's/,//'|cut -d':' -f2,3 | grep : > servert.txt; cat servert.txt | cut -d'.' -f2 > z.txt; cat servert.txt | cut -d':' -f1 | sed 's/00/0*60/' | sed 's/01/1*60/' | sed 's/02/2*60/' | sed 's/03/3*60/' | sed 's/04/4*60/' | sed 's/05/5*60/'| bc > x.txt; cat servert.txt | cut -d':' -f2 | cut -d'.' -f1 > y.txt; paste x.txt y.txt | expand | tr -s ' ' | tr ' ' '+' | bc > w.txt;  cat z.txt | tr ' ' 'x' >j.txt; paste w.txt j.txt | expand | tr -s ' ' | tr ' ' '.' | tr 'x' ' ' > servertf.txt; cat h1.txt | grep 5001 | grep -v ttl | tr -s ' ' | cut -d':' -f1 | cut -d'.' -f1-4 > ipo.txt; cat h1.txt | grep 5001 | grep -v ttl | tr -s ' ' | cut -d':' -f1 | cut -d' ' -f4 > ipd.txt; paste servertf.txt ipo.txt ipd.txt| expand | tr -s ' ' > server_etf.txt;  for i in {1..9}; do cat server_etf.txt | grep 10.0.0.$i > server_etf_sta$i\_$1.txt; done; cat server_etf_sta*_$1.txt | sort -n > result2/server_h1tf_sta_$1\_tt.txt

cat h2.txt | grep IP | sed 's/00:0/ 00:0/' | tr -s ' ' | cut -d' ' -f2,9,18 | cut -d')' -f1 | sed 's/,//'|cut -d':' -f2,3 | grep : > servert.txt; cat servert.txt | cut -d'.' -f2 > z.txt; cat servert.txt | cut -d':' -f1 | sed 's/00/0*60/' | sed 's/01/1*60/' | sed 's/02/2*60/' | sed 's/03/3*60/' | sed 's/04/4*60/' | sed 's/05/5*60/'| bc > x.txt; cat servert.txt | cut -d':' -f2 | cut -d'.' -f1 > y.txt; paste x.txt y.txt | expand | tr -s ' ' | tr ' ' '+' | bc > w.txt;  cat z.txt | tr ' ' 'x' >j.txt; paste w.txt j.txt | expand | tr -s ' ' | tr ' ' '.' | tr 'x' ' ' > servertf.txt; cat h2.txt | grep 5002 | grep -v ttl | tr -s ' ' | cut -d':' -f1 | cut -d'.' -f1-4 > ipo.txt; cat h2.txt | grep 5002 | grep -v ttl | tr -s ' ' | cut -d':' -f1 | cut -d' ' -f4 > ipd.txt; paste servertf.txt ipo.txt ipd.txt| expand | tr -s ' ' > server_e2tf.txt;  for i in {1..9}; do cat server_e2tf.txt | grep 10.0.0.$i > server_e2tf_sta$i\_$1.txt; done; cat server_e2tf_sta*_$1.txt | sort -n > result2/server_h2tf_sta_$1\_tt.txt

cat h3.txt | grep IP | sed 's/00:0/ 00:0/' | tr -s ' ' | cut -d' ' -f2,9,18 | cut -d')' -f1 | sed 's/,//'|cut -d':' -f2,3 | grep : > servert.txt; cat servert.txt | cut -d'.' -f2 > z.txt; cat servert.txt | cut -d':' -f1 | sed 's/00/0*60/' | sed 's/01/1*60/' | sed 's/02/2*60/' | sed 's/03/3*60/' | sed 's/04/4*60/' | sed 's/05/5*60/'|  bc > x.txt; cat servert.txt | cut -d':' -f2 | cut -d'.' -f1 > y.txt; paste x.txt y.txt | expand | tr -s ' ' | tr ' ' '+' | bc > w.txt;  cat z.txt | tr ' ' 'x' >j.txt; paste w.txt j.txt | expand | tr -s ' ' | tr ' ' '.' | tr 'x' ' ' > servertf.txt; cat h3.txt | grep 5003 | grep -v ttl | tr -s ' ' | cut -d':' -f1 | cut -d'.' -f1-4 > ipo.txt; cat h3.txt | grep 5003 | grep -v ttl | tr -s ' ' | cut -d':' -f1 | cut -d' ' -f4 > ipd.txt; paste servertf.txt ipo.txt ipd.txt| expand | tr -s ' ' > server_gtf.txt;  for i in {1..9}; do cat server_gtf.txt | grep 10.0.0.$i > server_gtf_sta$i\_$1.txt; done; cat server_gtf_sta*_$1.txt | sort -n > result2/server_h3tf_sta_$1\_tt.txt

#cat server_h?tf_sta*_$1.txt | sort -n > result2/server_stf_car_$1\_tt.txt

for i in {1..9}; do cat sta$i.txt | grep IP | grep -v ARP | grep -v ICMP| sed 's/00:0/ 00:0/' | tr -s ' ' | cut -d' ' -f2,9,18 | cut -d')' -f1 | sed 's/,//'|cut -d':' -f2,3 | grep : > cart.txt; cat cart.txt | cut -d'.' -f2 > z.txt; cat cart.txt | cut -d':' -f1 | sed 's/00/0*60/' | sed 's/01/1*60/' | sed 's/02/2*60/' | sed 's/03/3*60/'| sed 's/04/4*60/' | sed 's/05/5*60/'| bc > x.txt; cat cart.txt | cut -d':' -f2 | cut -d'.' -f1 > y.txt; paste x.txt y.txt | expand | tr -s ' ' | tr ' ' '+' | bc > w.txt;  cat z.txt | tr ' ' 'x' >j.txt; paste w.txt j.txt | expand | tr -s ' ' | tr ' ' '.' | tr 'x' ' ' > cartf.txt; echo $i; cat sta$i.txt | grep '>' | grep -v ICMP | tr -s ' ' | cut -d':' -f1 | cut -d'.' -f1-4 > ipo.txt; cat sta$i.txt | grep '>' | grep -v ICMP | tr -s ' ' | cut -d':' -f1 | cut -d' ' -f4 > ipd.txt; paste cartf.txt ipo.txt ipd.txt| expand | tr -s ' ' > car$(echo $i)tf_$1.txt; done 

#for i in $(ls car{7..14}\tf_$1.txt); do rm -f temp1.txt; rm -f temp2.txt; cp $i $i\.old; f=log$(echo $i | sed "s/tf_$1.txt//").txt; seg1=$(cat $f | grep ini | cut -d' ' -f2| cut -d'.' -f1); seg2=$(cat $f | grep transm | head -1 | cut -d' ' -f2| cut -d'.' -f1); k=$(($seg2 - $seg1)); for j in $(cat $i | cut -d'.' -f1); do echo $j+$k|bc >> temp1.txt; done; cat $i | cut -d'.' -f2-10 > temp2.txt; paste temp1.txt temp2.txt | expand | tr -s ' ' | sed 's/ /./' > $i; echo $i; done

for i in $(ls car*tf_$1.txt); do for j in {5001..5003}; do cat $i | grep "\.$j" | grep 1498 > $(echo $i | cut -d'.' -f1)_$j.txt; done; done

cat car*tf_$1\_5001.txt | sort -n > result2/cartf_$1\_5001_tt.txt; cat car*tf_$1\_5002.txt | sort -n > result2/cartf_$1\_5002_tt.txt; cat car*tf_$1\_5003.txt | sort -n > result2/cartf_$1\_5003_tt.txt


for i in $(ls ping*); do rm -f s.txt; x=$(cat ping3_h3.txt | grep 'PING' |cut -d' ' -f1 | head -1); for j in $(cat $i | grep 'from' |cut -d' ' -f1); do echo $x-$j | bc | sed 's/-//' >> s.txt; done; cat $i | grep 'from' | cut -d'=' -f4 | cut -d' ' -f1 > d.txt; paste s.txt d.txt | expand | tr -s ' ' > delay$(echo $i | cut -d'.' -f1 | sed 's/ping//')_$1.txt; done

cat delay*_h1_$1.txt |sort -n > result2/delay_h1_$1\_tt.txt; cat delay*_h2_$1.txt |sort -n > result2/delay_h2_$1\_tt.txt; cat delay*_h3_$1.txt |sort -n > result2/delay_h3_$1\_tt.txt

for i in $(ls logsta*.txt); do seg1=$(cat $i | grep ini | cut -d' ' -f2| cut -d'.' -f1); seg2=$(cat $i | grep transm | head -1 | cut -d' ' -f2| cut -d'.' -f1); j=$(($seg2 - $seg1));echo $i $j; done | cut -d' ' -f2 | sort -n > result2/temp_$1\_tt.txt